version: 0.2
         
phases:
  install:
    commands:
      - echo Installing nodejs 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run-script build
      - echo "Listing content..."
      - ls
      - ls ./build
      - cd build
      - pwd

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
  name: react-s3-$(date +%Y-%m-%d)
